version: '2'
services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    volumes_from:
      - box
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - './data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
  box:
    image: busybox
    volumes:
      - /bundle
