default: &default
  adapter: mysql2
  encoding: utf8
  database: spalah_development
  username: root
  password: rootpasswd
  host: db

development:
  <<: *default
  database: spalah_development

test:
  <<: *default
  database: spalah_test

production:
  <<: *default
  database: spalah_development
