default: &default
  adapter: mysql2
  encoding: utf8
  database: spalah_development
  pool: 25
  username: root
  password:

development:
  <<: *default
  database: spalah_development

test:
  <<: *default
  database: spalah_test

production:
  <<: *default
  database: spalah_development
